spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/movieflix
spring.datasource.username=postgres
spring.datasource.password=123456789

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

tmdb.api.key=c521298dcd6b4625968925fc0f5cd547
tmdb.base-url=https://api.themoviedb.org/3
movieflix.rental.duration-hours=48
